/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx,html}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "surface": "#0f172a",
        "surface-dim": "#0b0f19",
        "surface-bright": "#1e293b",
        "surface-container-lowest": "#0f172a",
        "surface-container-low": "#131c31",
        "surface-container": "#1e293b",
        "surface-container-high": "#334155",
        "surface-container-highest": "#475569",
        "on-surface": "#f8fafc",
        "on-surface-variant": "#94a3b8",
        "inverse-surface": "#f8fafc",
        "inverse-on-surface": "#0f172a",
        "outline": "#475569",
        "outline-variant": "#334155",
        "surface-tint": "#38bdf8",
        "primary": "#38bdf8",
        "on-primary": "#0b0f19",
        "primary-container": "#1e3a8a",
        "on-primary-container": "#dbeafe",
        "inverse-primary": "#0284c7",
        "secondary": "#f43f5e",
        "on-secondary": "#ffffff",
        "secondary-container": "#881337",
        "on-secondary-container": "#fecdd3",
        "tertiary": "#6366f1",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#312e81",
        "on-tertiary-container": "#e0e7ff",
        "error": "#ef4444",
        "on-error": "#ffffff",
        "error-container": "#7f1d1d",
        "on-error-container": "#fecaca",
        "primary-fixed": "#1e293b",
        "primary-fixed-dim": "#0f172a",
        "on-primary-fixed": "#f8fafc",
        "on-primary-fixed-variant": "#94a3b8",
        "secondary-fixed": "#881337",
        "secondary-fixed-dim": "#4c0519",
        "on-secondary-fixed": "#fecdd3",
        "on-secondary-fixed-variant": "#fda4af",
        "tertiary-fixed": "#312e81",
        "tertiary-fixed-dim": "#1e1b4b",
        "on-tertiary-fixed": "#e0e7ff",
        "on-tertiary-fixed-variant": "#c7d2fe",
        "background": "#0b0f19",
        "on-background": "#f8fafc",
        "surface-variant": "#1e293b"
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem"
      },
      spacing: {
        "stack-md": "16px",
        "margin-desktop": "32px",
        "stack-lg": "24px",
        "touch-target-min": "48px",
        "stack-sm": "8px",
        "gutter": "16px",
        "margin-mobile": "16px"
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "numeric-display": ["Inter", "sans-serif"]
      },
      fontSize: {
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "700" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "26px", fontWeight: "400" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "numeric-display": ["40px", { lineHeight: "48px", letterSpacing: "-0.03em", fontWeight: "700" }]
      }
    },
  },
  plugins: [],
}
