/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx,html}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "surface": "#f7faf9",
        "surface-dim": "#d7dbda",
        "surface-bright": "#f7faf9",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f1f4f3",
        "surface-container": "#ebeeed",
        "surface-container-high": "#e6e9e8",
        "surface-container-highest": "#e0e3e2",
        "on-surface": "#181c1c",
        "on-surface-variant": "#434749",
        "inverse-surface": "#2d3131",
        "inverse-on-surface": "#eef1f0",
        "outline": "#747879",
        "outline-variant": "#c3c7c8",
        "surface-tint": "#586062",
        "primary": "#181f21",
        "on-primary": "#ffffff",
        "primary-container": "#2d3436",
        "on-primary-container": "#959c9f",
        "inverse-primary": "#c1c8ca",
        "secondary": "#a83639",
        "on-secondary": "#ffffff",
        "secondary-container": "#ff7675",
        "on-secondary-container": "#720b16",
        "tertiary": "#152023",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#2a3538",
        "on-tertiary-container": "#929da2",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#dde4e6",
        "primary-fixed-dim": "#c1c8ca",
        "on-primary-fixed": "#161d1f",
        "on-primary-fixed-variant": "#41484a",
        "secondary-fixed": "#ffdad8",
        "secondary-fixed-dim": "#ffb3b0",
        "on-secondary-fixed": "#410006",
        "on-secondary-fixed-variant": "#881d24",
        "tertiary-fixed": "#d9e4e9",
        "tertiary-fixed-dim": "#bdc8cd",
        "on-tertiary-fixed": "#131d21",
        "on-tertiary-fixed-variant": "#3e484c",
        "background": "#f7faf9",
        "on-background": "#181c1c",
        "surface-variant": "#e0e3e2"
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem"
      },
      spacing: {
        "stack-md": "16px",
        "margin-desktop": "32px",
        "stack-lg": "24px",
        "touch-target-min": "48px",
        "stack-sm": "8px",
        "gutter": "16px",
        "margin-mobile": "16px"
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "numeric-display": ["Inter", "sans-serif"]
      },
      fontSize: {
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "700" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "26px", fontWeight: "400" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "numeric-display": ["40px", { lineHeight: "48px", letterSpacing: "-0.03em", fontWeight: "700" }]
      }
    },
  },
  plugins: [],
}
